name: firecorder
description: A sound recorder/player.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  path_provider: ^1.6.24
  record_mp3: ^2.1.0
  audioplayers: ^0.17.0
  provider: ^4.3.2+3
  firebase_core: ^0.5.3
  firebase_auth: "^0.18.4+1"
  firebase_storage: "^5.2.0"
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
